[build]
builder = "NIXPACKS"
nixpacksPlan = { "repo" = "punitarani/fli" }

[deploy]
numReplicas = 1
startCommand = "uv run fli-mcp"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
